### ISSUE TITLE
Failed to resolve dependencies

### ISSUE THREAD

**Issue by Abhi347** [mobilejazz/coltrane#10]
I am trying to use this library using gradle. All 3 dependencies have been failed to resolve. 
Here's what I am getting - 
![screen shot 2016-09-07 at 1 26 36 am](https://cloud.githubusercontent.com/assets/1445581/18288715/38f9a4aa-749a-11e6-8051-33b85fd0fd48.png)

Here's my dependencies - 

```
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:24.2.0'
    compile 'com.mobilejazz.coltrane:coltrane:0.2.0-SNAPSHOT@aar'
    compile 'com.mobilejazz.coltrane:coltrane-provider-filesystem:0.2.0-SNAPSHOT@aar'
    compile 'com.mobilejazz.coltrane:coltrane-ui:0.2.0-SNAPSHOT@aar'
}
```

It's a completely new project as I am trying to evaluate this library. Let me know if more information is required.

**Comment by joselufo** [comment]
Hello @Abhi347 

I checked in a blank project and everything was working, Did you forgot to add the maven snapshots repository URL in the build.gradle (root project)?

**build.gradle** (project folder)

```
allprojects {
  repositories {
    jcenter()
    mavenCentral()
    maven {
      url 'https://oss.sonatype.org/content/repositories/snapshots'
    }
  }
}
```

I will close the issue, feel free to reopen it if you couldn't use the library.

**Comment by yudikarma** [comment]
thanks. please add this information in your Readme document.
